### ISSUE TITLE
Google Analytics reporting metric filters

### ISSUE THREAD

**Issue by jrosell** [google/google-api-php-client-services#6]
$metricFilterSessions = new \Google_Service_AnalyticsReporting_MetricFilter();
$metricFilterSessions->setComparisonValue("100");

Translates to comparison_value JSON intead of comparisonValue https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet#metricfilter

**Comment by bshaffer** [comment]
I believe this has been fixed in the latest version. Can you confirm?

**Comment by jrosell** [comment]
I upgraded rto v0.3 and I still get same error.

Error calling POST https://analyticsreporting.googleapis.com/v4/reports:batchGet: (400) Invalid JSON payload received. Unknown name "comparison_value" at 'report_requests[0].metric_filter_clauses': Cannot find field.
Invalid JSON payload received. Unknown name "metric_name" at 'report_requests[0].metric_filter_clauses': Cannot find field.
Invalid value at 'report_requests[0].metric_filter_clauses.operator' (TYPE_ENUM), "GREATER_THAN"

My code:
$metricFilterSessions = new \Google_Service_AnalyticsReporting_MetricFilter();
$metricFilterSessions->setMetricName("ga:sessions");
$metricFilterSessions->setOperator("GREATER_THAN"); 
$metricFilterSessions->setComparisonValue("399");
...
$request = new \Google_Service_AnalyticsReporting_ReportRequest();
...
$request->setMetricFilterClauses($metricFilterSessions);

**Comment by bshaffer** [comment]
The issue is not with this library. If you look at the raw HTTP request you're making, it accurately reflects the expected JSON values:

```json
{
	"reportRequests": [{
		"metricFilterClauses": {
			"comparisonValue": "399",
			"metricName": "ga:sessions",
			"operator": "GREATER_THAN"
		}
	}]
}
```

However, if you use the [Analytics Reporting API Explorer](https://developers.google.com/apis-explorer/#p/analyticsreporting/v4/analyticsreporting.reports.batchGet), you'll see the structure should actually look like this:

```json
{
	"reportRequests": [{
		"viewId": 1,
		"metricFilterClauses": [{
			"filters": [{
				"comparisonValue": "399",
				"metricName": "ga:sessions",
				"operator": "GREATER_THAN"
			}]
		}]
	}]
}
```

The difference here is the `filter` clause, the `viewId`, and some nested arrays. This is an issue with the library, that we are not type-checking these. I'll look into fixing that. However, the error you're seeing using the snake-cased variables are coming from the Analytics API, so the formatting difference is in the error, and not the request.

Try something like this instead:

```php
// create the client
$client = new Google_Client();
$client->setAuthConfig($credentialsFile);
$client->setApplicationName("Client_Library_Examples");
$client->setScopes([Google_Service_AnalyticsReporting::ANALYTICS]);

// create the metric filter
$metricFilterSessions = new Google_Service_AnalyticsReporting_MetricFilter();
$metricFilterSessions->setMetricName("ga:sessions");
$metricFilterSessions->setOperator("GREATER_THAN");
$metricFilterSessions->setComparisonValue("399");
$metricFilterClause = new Google_Service_AnalyticsReporting_MetricFilterClause();
$metricFilterClause->setFilters([$metricFilterSessions]);

// create the report requests
$reportRequest = new Google_Service_AnalyticsReporting_ReportRequest();
$reportRequest->setMetricFilterClauses([$metricFilterClause]);
$reportRequest->setViewId($yourViewId); // you have to set your own View ID here!!
$getReportsRequest = new Google_Service_AnalyticsReporting_GetReportsRequest();
$getReportsRequest->setReportRequests([$reportRequest]);

// make the call
$service = new Google_Service_AnalyticsReporting($client);
$results = $service->reports->batchGet($getReportsRequest);
```

I hope this helps!
